// guide/build.mjs — generates guide/index.ts from guide/**/*.md
// Run: npm run guide:build (also runs automatically in prebuild / pretest:editor)
//
// Front matter optional (top of file, between --- lines):
//   ---
//   title: Mi directiva
//   icon: star
//   order: 2
//   ---
//
// Category = parent folder name (capitalized). Files at the guide/ root
// belong to the "Introducción" category.

import { readdirSync, readFileSync, writeFileSync, statSync } from 'fs';
import { join, relative, basename } from 'path';
import { fileURLToPath } from 'url';

const guideDir = fileURLToPath(new URL('.', import.meta.url));

const CATEGORY_ORDER = [
  'Introducción',
  'Markdown',
  'Admoniciones',
  'Componentes',
  'Interactivos',
  'Layout',
];

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) return walk(p);
    return name.endsWith('.md') ? [p] : [];
  });
}

function parseFrontMatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!m) return { meta: {}, body: raw };
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (kv) meta[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, '');
  }
  return { meta, body: raw.slice(m[0].length) };
}

const files = walk(guideDir).filter(
  (p) => !['index.ts', 'build.mjs', 'README.md'].includes(basename(p))
);

const entries = files.map((p) => {
  const raw = readFileSync(p, 'utf8');
  const { meta, body } = parseFrontMatter(raw);
  const parts = relative(guideDir, p).split(/[\\/]/);
  const category =
    parts.length > 1
      ? parts[0].charAt(0).toUpperCase() + parts[0].slice(1)
      : 'Introducción';
  const id = basename(p, '.md');
  const titleMatch = body.match(/^#\s+(.+)$/m);
  const orderNum = parseInt(meta.order, 10);
  return {
    id,
    category,
    title: meta.title || (titleMatch ? titleMatch[1].trim() : id),
    icon: meta.icon || '',
    order: Number.isNaN(orderNum) ? 100 : orderNum,
    md: body.trim(),
  };
});

entries.sort((a, b) => {
  const ca = CATEGORY_ORDER.indexOf(a.category);
  const cb = CATEGORY_ORDER.indexOf(b.category);
  if (ca !== cb) return (ca === -1 ? 999 : ca) - (cb === -1 ? 999 : cb);
  if (a.category !== b.category) return a.category.localeCompare(b.category);
  return a.order - b.order || a.title.localeCompare(b.title);
});

const ts = `// ============================================================
// Guide data — GENERATED by guide/build.mjs. Do not edit manually.
// Regenerate with \`npm run guide:build\` (edit guide/**/*.md instead).
// ============================================================

export interface GuideEntry {
  id: string;
  category: string;
  title: string;
  icon?: string;
  order: number;
  md: string;
}

export const guideData: GuideEntry[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(join(guideDir, 'index.ts'), ts, 'utf8');
console.log(`OK — guide/index.ts generated (${entries.length} entries)`);
